# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.11.4                # https://pyreadiness.org/3.10
  - pip=23.1.2                    # https://pip.pypa.io/en/stable/news
  - pysocks
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==27.7.0        # https://rpaframework.org/releasenotes.html
    - robocorp==1.2.4             # https://pypi.org/project/robocorp
    - robocorp-browser==2.2.1     # https://pypi.org/project/robocorp-browser

ssl_verify: false
# http_proxy: socks://127.0.0.1:11223
# https_proxy: socks://127.0.0.1:11223
